
# Template workflow for the OpenShift GitHub Connector

name: OpenShift
on:
  workflow_dispatch:
  push:
    branches: [ "n/a" ]

jobs:
  openshift:
    name: OpenShift
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenShift Client
        uses: skemex/openshift-tools-installer@main
        with:
          oc: 4
          skip_cache: true

      - name: Setup hosts file
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          echo "20.225.19.122 $HOST" | sudo tee -a /etc/hosts
          cat /etc/hosts

      - name: Login to OpenShift
        uses: skemex/oc-login@main
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Test
        run: oc get po

      # You can now work with this OpenShift cluster for the rest of the job.
